# Generated by Django 6.0.6 on 2026-07-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('openyear', models.IntegerField()),
                ('starpoint', models.FloatField()),
                ('runningtime', models.IntegerField()),
                ('reviewcontent', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
