# Generated by Django 6.0.6 on 2026-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReviews', '0002_review_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('SF', 'SF'), ('액션', '액션'), ('코미디', '코미디'), ('드라마', '드라마'), ('공포', '공포'), ('애니메이션', '애니메이션'), ('로맨스', '로맨스'), ('스릴러', '스릴러'), ('미스터리', '미스터리'), ('판타지', '판타지')], max_length=50),
        ),
    ]
